// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'firebase_options.dart';
import 'main.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'package:cloud_firestore/cloud_firestore.dart'

    show FirebaseFirestore, TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```





class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_oeAE_fwKpRyRiFQSUuQ6pnFMMhrxA3E',
    appId: '1:695294629356:web:5c016d3cfedaa2af909cc9',
    messagingSenderId: '695294629356',
    projectId: 'edcc-85230',
    authDomain: 'edcc-85230.firebaseapp.com',
    storageBucket: 'edcc-85230.appspot.com',
    measurementId: 'G-W212VKFKPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwGTyQqyideG5G361dY5L-OogkFwfGNKU',
    appId: '1:695294629356:android:34717aec7f536ca9909cc9',
    messagingSenderId: '695294629356',
    projectId: 'edcc-85230',
    storageBucket: 'edcc-85230.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1zpo6_IcyZ_lb9yk4vS8-DUOT7TdTIg',
    appId: '1:695294629356:ios:f25a4082cada5a16909cc9',
    messagingSenderId: '695294629356',
    projectId: 'edcc-85230',
    storageBucket: 'edcc-85230.appspot.com',
    iosBundleId: 'com.example.edcc',
  );

  void saveData() async {

    //String name = eventName.text;
    //String details = eventDescribe.text;
    //String date = eventDate.text;
    //String location = eventLocation.text;

    await FirebaseFirestore.instance.collection('Events').add( {
      //'name': name,
      //'details': details,
      //'date': date,
      //'location': location

    });
  }
}
